Fixed the bash syntax error
izgzhen/markii pull request #45
Opened 2020-08-12 07:56 UTC by LuxiWang99

2020-08-13 01:27 UTC, izgzhen approved these changes

2020-08-13 01:28 UTC, izgzhen requested changes
Emm, check CI failure. You probably need to fix more @LuxiWang99

2020-08-13 01:30 UTC, izgzhen commented on build-run-markii.sh
> +TEMPFILE_REMOVE=$3
`$3` might be empty. Set it to a default value:

```bash
if [ -z "$3" ]; then
    TEMPFILE_REMOVE=...
else
    TEMPFILE_REMOVE=$3
fi
```

Test it though, I am not sure I wrote it in the right way

2020-08-14 11:45 UTC, LuxiWang99 reviewed
updated in the most recent commit

2020-08-14 17:46 UTC, izgzhen approved these changes

2020-08-14 17:46 UTC, merged